import React from 'react';
import CritterAvatar from '../components/CritterAvatar';
import { DEFAULT_PREFERENCES, type PlaytimeDuration, useAudioPreferences } from '../game/audioPreferences';
import { syncSeasonalSoundscape } from '../game/seasonalSoundscape';
import { CAMP_THEME_DETAILS, resolveCampTheme } from '../game/campThemes';
import { LEARNING_THEME_DETAILS } from '../game/learningThemes';
import { playButton } from '../game/sounds';

interface Props { onBack: () => void; onOpenProgress: () => void; onOpenGallery: () => void; }

export default function ParentSettingsScreen({ onBack, onOpenProgress, onOpenGallery }: Props) {
  const [preferences, savePreferences] = useAudioPreferences();
  const volume = Math.round(preferences.voiceVolume * 100);
  const soundscapeVolume = Math.round(preferences.soundscapeVolume * 100);
  const saveSoundscape = (next: typeof preferences) => { savePreferences(next); syncSeasonalSoundscape(next, resolveCampTheme(next.campTheme)); };

  return <div className="game-screen forest-bg overflow-y-auto px-4 pb-8">
    <header className="flex items-center justify-between pt-safe pt-4 pb-3">
      <div className="flex items-center gap-2"><CritterAvatar type="owl" size={44} expression="happy" /><div><p className="font-body text-[10px] uppercase tracking-[.14em] text-white/65">Grown-up space</p><h1 className="font-display text-xl font-bold text-white">Parent Settings</h1></div></div>
      <button onClick={() => { playButton(); onBack(); }} className="paper-card px-3 py-1.5 text-sm font-body text-[#2D2418] active:scale-95">Back to camp</button>
    </header>
    <main className="mx-auto w-full max-w-md space-y-3">
      <section className="paper-card p-4"><h2 className="font-display text-[#2D2418] font-bold text-lg">Character voices</h2><p className="font-body text-xs text-[#5C4D3C] mt-1">Voices play only after a child taps a clearly labelled button.</p><label className="mt-4 flex items-center gap-2"><span className="font-body text-sm text-[#49392C] whitespace-nowrap">Voice volume</span><input aria-label="Character voice volume" type="range" min="0" max="100" value={volume} onChange={(event) => savePreferences({ ...preferences, voiceVolume: Number(event.target.value) / 100 })} className="flex-1 accent-[#E66B5B]" /><span className="font-body text-xs text-[#5C4D3C] w-8 text-right">{volume}%</span></label></section>
      <section className="paper-card p-4"><h2 className="font-display text-[#2D2418] font-bold text-lg">Words on screen</h2><p className="font-body text-xs text-[#5C4D3C] mt-1">Keep spoken character lines visible during rescues.</p><label className="mt-3 flex items-center justify-between gap-3 cursor-pointer"><span className="font-body text-sm font-bold text-[#49392C]">Show story words</span><input aria-label="Show spoken dialogue as captions" type="checkbox" checked={preferences.captionsEnabled} onChange={(event) => savePreferences({ ...preferences, captionsEnabled: event.target.checked })} className="h-5 w-5 accent-[#E66B5B]" /></label></section>
      <section className="paper-card p-4"><h2 className="font-display text-[#2D2418] font-bold text-lg">Spoken directions</h2><p className="font-body text-xs text-[#5C4D3C] mt-1">Shows optional “Hear directions” buttons in onboarding, rescues, the Daily Trail, and learning play. Turning it off keeps visual prompts and captions available.</p><label className="mt-3 flex items-center justify-between gap-3 cursor-pointer"><span className="font-body text-sm font-bold text-[#49392C]">Offer spoken directions</span><input aria-label="Offer optional spoken directions" type="checkbox" checked={preferences.spokenDirectionsEnabled} onChange={(event) => savePreferences({ ...preferences, spokenDirectionsEnabled: event.target.checked })} className="h-5 w-5 accent-[#E66B5B]" /></label></section>
      <section className="paper-card p-4"><h2 className="font-display text-[#2D2418] font-bold text-lg">Seasonal soundscape</h2><p className="font-body text-xs text-[#5C4D3C] mt-1">A quiet seasonal woodland loop for the camp. It is off unless a grown-up chooses to turn it on.</p><label className="mt-3 flex items-center justify-between gap-3 cursor-pointer"><span className="font-body text-sm font-bold text-[#49392C]">Play gentle background sound</span><input aria-label="Play seasonal background soundscape" type="checkbox" checked={preferences.soundscapeEnabled} onChange={(event) => saveSoundscape({ ...preferences, soundscapeEnabled: event.target.checked })} className="h-5 w-5 accent-[#E66B5B]" /></label><label className="mt-4 flex items-center gap-2"><span className="font-body text-sm text-[#49392C] whitespace-nowrap">Background level</span><input aria-label="Seasonal soundscape volume" disabled={!preferences.soundscapeEnabled} type="range" min="0" max="45" value={soundscapeVolume} onChange={(event) => saveSoundscape({ ...preferences, soundscapeVolume: Number(event.target.value) / 100 })} className="flex-1 accent-[#6EB9CE] disabled:opacity-40" /><span className="font-body text-xs text-[#5C4D3C] w-8 text-right">{soundscapeVolume}%</span></label></section>
      <section className="paper-card p-4"><h2 className="font-display text-[#2D2418] font-bold text-lg">Sanctuary look</h2><p className="font-body text-xs text-[#5C4D3C] mt-1">Choose a gentle camp season. “Follow the season” keeps the sanctuary automatic.</p><label className="mt-3 block"><span className="font-body text-sm font-bold text-[#49392C]">Camp theme</span><select aria-label="Choose seasonal sanctuary theme" value={preferences.campTheme} onChange={(event) => saveSoundscape({ ...preferences, campTheme: event.target.value as typeof preferences.campTheme })} className="mt-2 w-full rounded-xl border border-[#D5C3A8] bg-[#FFF9EF] px-3 py-2.5 font-body text-sm text-[#49392C]">{Object.entries(CAMP_THEME_DETAILS).map(([key, detail]) => <option key={key} value={key}>{detail.icon} {detail.label}</option>)}</select></label><p className="mt-2 font-body text-[11px] text-[#5C4D3C]">Now showing: {CAMP_THEME_DETAILS[preferences.campTheme].icon} {CAMP_THEME_DETAILS[preferences.campTheme].description}</p></section>
      <section className="paper-card p-4"><h2 className="font-display text-[#2D2418] font-bold text-lg">Learning focus</h2><p className="font-body text-xs text-[#5C4D3C] mt-1">Choose a gentle idea to spotlight. Every learning activity stays available and there are no scores or locks.</p><label className="mt-3 block"><span className="font-body text-sm font-bold text-[#49392C]">Today’s family focus</span><select aria-label="Choose family learning focus" value={preferences.learningTheme} onChange={(event) => savePreferences({ ...preferences, learningTheme: event.target.value as typeof preferences.learningTheme })} className="mt-2 w-full rounded-xl border border-[#D5C3A8] bg-[#FFF9EF] px-3 py-2.5 font-body text-sm text-[#49392C]">{Object.entries(LEARNING_THEME_DETAILS).map(([key, detail]) => <option key={key} value={key}>{detail.icon} {detail.label}</option>)}</select></label><p className="mt-2 font-body text-[11px] text-[#5C4D3C]">{LEARNING_THEME_DETAILS[preferences.learningTheme].description}</p></section>
      <section className="paper-card p-4"><h2 className="font-display text-[#2D2418] font-bold text-lg">Quiet ending reminder</h2><p className="font-body text-xs text-[#5C4D3C] mt-1">Shows one small optional “Rest” card in camp after a rescue. It has no timer, countdown, or child-facing demand.</p><label className="mt-3 flex items-center justify-between gap-3 cursor-pointer"><span className="font-body text-sm font-bold text-[#49392C]">Offer a quiet bedtime card</span><input aria-label="Offer optional bedtime reminder card" type="checkbox" checked={preferences.bedtimeReminderEnabled} onChange={(event) => savePreferences({ ...preferences, bedtimeReminderEnabled: event.target.checked })} className="h-5 w-5 accent-[#6377A8]" /></label></section>
      <section className="paper-card p-4"><h2 className="font-display text-[#2D2418] font-bold text-lg">Gentle playtime check-in</h2><p className="font-body text-xs text-[#5C4D3C] mt-1">After the time you choose, camp can offer one small “Would a rest feel good?” card. It never locks play, shows a countdown, or asks a child to decide alone.</p><label className="mt-3 block"><span className="font-body text-sm font-bold text-[#49392C]">Offer a rest suggestion after</span><select aria-label="Choose gentle playtime duration" value={preferences.playtimeDurationMinutes} onChange={(event) => savePreferences({ ...preferences, playtimeDurationMinutes: Number(event.target.value) as PlaytimeDuration })} className="mt-2 w-full rounded-xl border border-[#D5C3A8] bg-[#FFF9EF] px-3 py-2.5 font-body text-sm text-[#49392C]"><option value={0}>Off</option><option value={10}>About 10 minutes</option><option value={20}>About 20 minutes</option><option value={30}>About 30 minutes</option></select></label></section>
      <section className="paper-card p-4"><h2 className="font-display text-[#2D2418] font-bold text-lg">Large-icon mode</h2><p className="font-body text-xs text-[#5C4D3C] mt-1">Makes plushie pictures bigger across the game, so they are easier to spot.</p><label className="mt-3 flex items-center justify-between gap-3 cursor-pointer"><span className="font-body text-sm font-bold text-[#49392C]">Use bigger plushies</span><input aria-label="Use large-icon mode" type="checkbox" checked={preferences.largeIconMode} onChange={(event) => savePreferences({ ...preferences, largeIconMode: event.target.checked })} className="h-5 w-5 accent-[#E66B5B]" /></label></section>
      <section className="paper-card p-4"><h2 className="font-display text-[#2D2418] font-bold text-lg">Reduce motion</h2><p className="font-body text-xs text-[#5C4D3C] mt-1">Stops bouncy plushies, floating fireflies, flickering lights, page fades, and other nonessential motion. The game stays fully playable.</p><label className="mt-3 flex items-center justify-between gap-3 cursor-pointer"><span className="font-body text-sm font-bold text-[#49392C]">Use less movement</span><input aria-label="Reduce nonessential game motion" type="checkbox" checked={preferences.reduceMotion} onChange={(event) => savePreferences({ ...preferences, reduceMotion: event.target.checked })} className="h-5 w-5 accent-[#E66B5B]" /></label></section>
      <button onClick={() => { playButton(); onOpenProgress(); }} className="w-full rounded-xl px-4 py-3 text-left active:scale-[.98]" style={{ background: '#F8E8D8', border: '1px solid #E2C9AB' }}><p className="font-body text-[10px] uppercase tracking-[.14em] text-[#A85C41] font-bold">Grown-up view</p><p className="font-display text-[#2D2418] font-bold text-base mt-0.5">Open learning & activity summary →</p></button>
      <button onClick={() => { playButton(); onOpenGallery(); }} className="w-full rounded-xl px-4 py-3 text-left active:scale-[.98]" style={{ background: '#EAF4EF', border: '1px solid #B9D9C2' }}><p className="font-body text-[10px] uppercase tracking-[.14em] text-[#3D7A58] font-bold">Grown-up view</p><p className="font-display text-[#2D2418] font-bold text-base mt-0.5">Open family keepsake gallery →</p><p className="mt-1 font-body text-[10px] text-[#5C4D3C]">Illustrated in-game memories only — no child photos, voice, sharing, or uploads.</p></button>
      <button onClick={() => savePreferences(DEFAULT_PREFERENCES)} className="w-full rounded-xl py-2 font-body text-sm text-white/85 active:scale-95" style={{ background: 'rgba(255,255,255,.14)', border: '1px solid rgba(255,255,255,.22)' }}>Reset to game defaults</button>
      <p className="font-body text-center text-[10px] text-white/55 px-5">These settings are saved on this device. They change how the game looks and sounds, not the rescue progress.</p>
    </main>
  </div>;
}
