import { AlertTriangle, ArrowRight, Check, CheckCircle2, ClipboardCheck, MessageSquareText, Sparkles, Timer, UserRound } from "lucide-react";
import { useState } from "react";

type View = "client" | "coach";

const loop = [
  ["1", "Client reports", "A missed action and lower capacity are stated plainly."],
  ["2", "Route offers choices", "Keep the date, move it, reduce scope, or change sequence."],
  ["3", "Coach decides", "The change and trade-off are visible before approval."],
  ["4", "Next session is ready", "The brief surfaces decisions and blockers—not just a percentage."],
] as const;

export default function PublicDemo() {
  const [view, setView] = useState<View>("coach");
  const [approved, setApproved] = useState(false);

  return <section id="demo" className="border-y border-[#dce5df] bg-[#edf5f0] px-5 py-20 lg:px-8 lg:py-28">
    <div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="eyebrow">Public fictional walkthrough</p><h2 className="mt-3 text-4xl font-semibold tracking-[-.055em] sm:text-5xl">See the coaching loop before you sign in.</h2><p className="mt-5 text-lg leading-8 text-[#567178]">One fictional business client. One missed action. One coach decision. This illustrates the workflow only—no private workspace data is shown.</p></div>
      <div className="mt-10 flex flex-wrap gap-2 rounded-2xl border border-[#d7e4dd] bg-white p-2"><button aria-pressed={view === "coach"} onClick={() => setView("coach")} className={`inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold transition ${view === "coach" ? "bg-[#102a31] text-white" : "text-[#587177] hover:bg-[#eff6f2]"}`}><UserRound size={16} /> Coach view</button><button aria-pressed={view === "client"} onClick={() => setView("client")} className={`inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold transition ${view === "client" ? "bg-[#102a31] text-white" : "text-[#587177] hover:bg-[#eff6f2]"}`}><ClipboardCheck size={16} /> Client view</button><span className="ml-auto self-center px-3 text-xs font-bold text-[#6b8588]">Fictional example</span></div>
      <div className="mt-5 grid gap-5 lg:grid-cols-[1.12fr_.88fr]">{view === "client" ? <ClientView /> : <CoachView approved={approved} onApprove={() => setApproved(true)} />}
        <aside className="rounded-[1.5rem] bg-[#102a31] p-6 text-white sm:p-7"><p className="text-[10px] font-black tracking-[.16em] text-[#8cd3c2]">WHAT THE LOOP PROTECTS</p><h3 className="mt-3 text-2xl font-semibold tracking-tight">A missed action is information, not a failed goal.</h3><div className="mt-7 space-y-5">{loop.map(([number, title, body]) => <div key={number} className="flex gap-4"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full border border-[#65b9a6] text-xs font-black text-[#a7e1d3]">{number}</span><div><p className="font-bold">{title}</p><p className="mt-1 text-sm leading-6 text-[#b6cccc]">{body}</p></div></div>)}</div><p className="mt-8 border-t border-white/10 pt-5 text-sm leading-6 text-[#c7d6d5]">While approval is pending, the client keeps a clear protected action rather than receiving a silent new plan.</p></aside></div>
    </div>
  </section>;
}

function ClientView() {
  return <article className="rounded-[1.5rem] border border-[#d7e4dd] bg-white p-6 shadow-[0_16px_45px_rgba(17,55,49,.07)] sm:p-8"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="eyebrow">Jane’s client portal</p><h3 className="mt-2 text-2xl font-semibold tracking-tight">Launch consulting offer</h3></div><span className="rounded-full bg-[#fff1dc] px-3 py-1.5 text-xs font-bold text-[#9a5d12]">Low capacity</span></div><div className="mt-7 rounded-2xl border border-[#cfe5dc] bg-[#f4fbf7] p-5"><p className="text-[10px] font-black tracking-[.14em] text-[#13776d]">TODAY — KEEP MOVING</p><p className="mt-2 text-lg font-bold">Write the pricing outline for 20 minutes.</p><p className="mt-2 text-sm leading-6 text-[#59767a]">The route protects one essential action while the coach reviews the requested change.</p><div className="mt-4 flex items-center gap-2 text-sm font-bold text-[#0e746a]"><Timer size={16} /> 20 minutes · protected priority</div></div><div className="mt-5 rounded-2xl border border-[#efd8ad] bg-[#fff9ee] p-5"><div className="flex gap-3"><AlertTriangle className="mt-0.5 shrink-0 text-[#a76715]" size={19} /><div><p className="font-bold text-[#7b531d]">Jane reported a blocker.</p><p className="mt-1 text-sm leading-6 text-[#775f42]">“Client calls ran over this week. I completed the outline but missed outreach.”</p></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><button className="rounded-xl border border-[#d7deda] bg-white px-3 py-2.5 text-left text-sm font-bold text-[#4d696d]">Keep destination</button><button className="rounded-xl border-2 border-[#0f766e] bg-[#e7f5ef] px-3 py-2.5 text-left text-sm font-bold text-[#0f766e]">Reduce scope <span className="block text-xs font-medium">Selected for review</span></button></div></div></article>;
}

function CoachView({ approved, onApprove }: { approved: boolean; onApprove: () => void }) {
  return <article className="rounded-[1.5rem] border border-[#d7e4dd] bg-white p-6 shadow-[0_16px_45px_rgba(17,55,49,.07)] sm:p-8"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="eyebrow">Northstar Coaching — approval queue</p><h3 className="mt-2 text-2xl font-semibold tracking-tight">Jane’s route needs a decision.</h3></div><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${approved ? "bg-[#ddf2ea] text-[#11675f]" : "bg-[#fff1dc] text-[#9a5d12]"}`}>{approved ? "Approved" : "Awaiting coach"}</span></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-[#f6f7f4] p-5"><p className="text-[10px] font-black tracking-[.13em] text-[#6a8587]">SYSTEM DATA</p><p className="mt-2 text-sm font-bold">3 of 5 actions complete</p><p className="mt-1 text-sm text-[#617a7e]">1 action missed · capacity changed to low</p></div><div className="rounded-2xl bg-[#fff8eb] p-5"><p className="text-[10px] font-black tracking-[.13em] text-[#8f621f]">CLIENT-REPORTED</p><p className="mt-2 text-sm leading-6 text-[#6f5b3d]">Client calls overran; outreach did not happen.</p></div></div><div className="mt-4 rounded-2xl border border-[#cce4da] bg-[#f4fbf7] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-black tracking-[.13em] text-[#11766c]">PROPOSED ADJUSTMENT</p><p className="mt-2 font-bold">Reduce scope: protect pricing, postpone outreach one week.</p><p className="mt-1 text-sm leading-6 text-[#597479]">Consequence: destination remains visible; next week’s workload drops by one non-critical action.</p></div>{approved ? <span className="inline-flex items-center gap-1.5 rounded-lg bg-[#0f766e] px-3 py-2 text-sm font-bold text-white"><Check size={15} /> Route updated</span> : <button onClick={onApprove} className="vr-button">Approve adjustment <ArrowRight size={16} /></button>}</div></div><div className="mt-5 rounded-2xl bg-[#102a31] p-5 text-white"><div className="flex items-center gap-2"><MessageSquareText size={17} className="text-[#8ed4c4]" /><p className="text-[10px] font-black tracking-[.14em] text-[#a9d9ce]">NEXT-SESSION BRIEF</p></div><p className="mt-3 font-bold">Discuss the client-call load before adding outreach back.</p><p className="mt-1 text-sm leading-6 text-[#bfd1d0]">AI interpretation is labelled separately; the coach keeps the decision.</p></div></article>;
}
